---
apiVersion: v1
kind: Pod
metadata:
  name: chatpod
spec:
  hostNetwork: true
  containers:
    - name: chat-server
      image: chat:latest
      imagePullPolicy: Never
    - name: nginx-reverse-proxy
      image: nginx:latest
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-configmap
