apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    upstream backend {
      server localhost:3000;
    }
    
    server {
      listen 80;
      listen [::]:80;
      server_name localhost;
    
      include /etc/nginx/conf.d/common-proxy-settings.conf;
    
      location / {
        proxy_pass http://backend/;
      }
    
      location /chat {
        proxy_pass http://backend/chat;
      }
    
      location /login {
        proxy_pass http://backend/login;
      }
    }
  common-proxy-settings.conf: |
    proxy_set_header Cookie $http_cookie;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
