apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    upstream backend {
      server chat-server;
    }

    server {
        listen       80;
        listen  [::]:80;
        server_name  omriz_chat.com;

        location / {
            proxy_pass http://chat-server:3000/;
      proxy_set_header Cookie $http_cookie;
      proxy_read_timeout 300s;
      proxy_send_timeout 300s;
      proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /chat {
            proxy_pass http://chat-server:3000/chat;
      proxy_set_header Cookie $http_cookie;
      proxy_read_timeout 300s;
      proxy_send_timeout 300s;
      proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /login {
            proxy_pass http://chat-server:3000/login;
      proxy_set_header Cookie $http_cookie;
      proxy_read_timeout 300s;
      proxy_send_timeout 300s;
      proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }