---
version: "3"
services:
  chat:
    image: chat:latest
    container_name: chat-server
    ports:
      - 3000:3000
    networks:
      - chat-network
  nginx_reverse_proxy:
    image: nginx
    container_name: reverse_proxy
    volumes:
      - ./reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - chat-network
networks:
  chat-network:
    driver: bridge
